# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
pod 'SwiftSVG', '~> 2.0'
  # Pods for Assignment

  target 'AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
